### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yagoag** [mat3e/olingo-jpa#1]
I loved the helpers and want to use them in a project I'm currently working on, but I can't since the project doesn't have a license.
Is it possible for you to add a license to your project so I can check with the company whether we can use it in our company's project?

**Comment by mat3e** [comment]
Hi,
thanks for your post. I'm not limiting the usage of helpers. Feel free to contribute.

The example usage is published [here](https://github.com/sollersconsulting/confitura2017).

**Comment by yagoag** [comment]
Thank you very much! I sure will contribute if I can.
